# Generated by Django 3.2.5 on 2021-07-03 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buffet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('url', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('mentor', models.CharField(blank=True, max_length=80, null=True, verbose_name='Ментор')),
                ('assistant', models.CharField(blank=True, max_length=80, null=True, verbose_name='Ассистент')),
                ('classroom', models.CharField(max_length=50, verbose_name='Номер кабинета')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('pin', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Пин')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер')),
                ('pin', models.CharField(max_length=6, unique=True, verbose_name='ПИН')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Номер телефона')),
                ('pin', models.CharField(max_length=8, unique=True, verbose_name='Пин')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_school.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('summ', models.FloatField()),
                ('debt_sum', models.FloatField()),
                ('status', models.BooleanField(choices=[(True, 'Открыт'), (False, 'Закрыт'), (3, 'Списан')], default=True, verbose_name='Статус')),
                ('pin_pins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_school.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Oper_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('id_buffet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_school.buffet')),
                ('id_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_school.operations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
